# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
- task: PublishBuildArtifacts@1
    
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(0de197d3-4c42-43c7-9207-b8c2bf1be2c8)'
    appType: 'webAppLinux'
    appName: 'azurename'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'TOMCAT|9.0-jre8'